name: Publish
on :
  workflow_dispatch:
  push:
    branches: 
    - master

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: dev1ops
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4  
    
    - name: Setup .Net
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore   ./demoDevOps.sln

    - name: Build
      run: dotnet build ./demoDevOps.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./demoDevOps.sln  --configuration Release --no-build --output '${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

