name: Publish
on :
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4  
    
    - name: Setup .Net
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore  $SOLUTION

    - name: Build
      run: dotnet build  $SOLUTION --configuration Release --no-restore

    - name: Publish
      run: dotnet publish $SOLUTION  --configuration Release --no-build
    
